<?php

require_once __DIR__ . '/schedulefield.crud.inc';
require_once __DIR__ . '/schedulefield.field.inc';
require_once __DIR__ . '/schedulefield.field_formatter.inc';
require_once __DIR__ . '/schedulefield.field_widget.inc';

/**
 * Implements hook_theme().
 */
function schedulefield_theme() {
  return [
    'schedulefield_formatter' => [
      'variables' => ['item' => []],
    ],
  ];
}

/**
 * Returns available periods in a day.
 *
 * @return
 *   An array of available periods in a day keyed by period key and containing
 *   period human name.
 */
function schedulefield_get_periods() {
  $periods =& drupal_static(__FUNCTION__, []);
  if (!$periods) {
    $periods = [
      'morning'   => t('Morning'),
      'afternoon' => t('Afternoon'),
    ];
    drupal_alter('schedule_field_periods', $periods);
  }
  return $periods;
}

/**
 * Function helper to get dayname from a given day week number.
 */
function schedulefield_get_dayname($day_week) {
  $day_weeks = [
      0 => t('Sunday'),
      1 => t('Monday'),
      2 => t('Tuesday'),
      3 => t('Wednesday'),
      4 => t('Thursday'),
      5 => t('Friday'),
      6 => t('Saturday'),
  ];
  return isset($day_weeks[$day_week]) ? $day_weeks[$day_week] : '';
}
