<?php

require_once __DIR__ . '/schedulefield.crud.inc';
require_once __DIR__ . '/schedulefield.field.inc';
require_once __DIR__ . '/schedulefield.field_formatter.inc';
require_once __DIR__ . '/schedulefield.field_widget.inc';

/**
 * Implements hook_theme().
 */
function schedulefield_theme() {
  return [
    'schedulefield_formatter' => [
      'variables' => ['item' => []],
    ],
  ];
}

/**
 * Returns available slots in a day.
 *
 * @return
 *   An array of available slots in a day keyed by slot key and containing
 *   the slot readable name.
 */
function schedulefield_get_slots() {
  $slots =& drupal_static(__FUNCTION__, []);
  if (!$slots) {
    $slots = [
      'morning'   => t('Morning'),
      'afternoon' => t('Afternoon'),
    ];
    drupal_alter('schedule_field_slots', $slots);
  }
  return $slots;
}

/**
 * Function helper to get day name from a given week day number.
 */
function schedulefield_get_day_name($day) {
  $week = [
    0 => t('Sunday'),
    1 => t('Monday'),
    2 => t('Tuesday'),
    3 => t('Wednesday'),
    4 => t('Thursday'),
    5 => t('Friday'),
    6 => t('Saturday'),
  ];
  return isset($week[$day]) ? $week[$day] : '';
}
